### ISSUE TITLE
Has This Been Proposed Upstream?

### ISSUE THREAD

**Issue by stevekuznetsov** [mkokho/kubemrr#2]
I've run into similar latency issues with the completion functions, but I've not seen this project before. Has this idea been proposed upstream? Seems like it would be generally useful for the k8s project as a whole.

**Comment by mkokho** [comment]
Thanks for the interest :)
Nope, I wanted to try in our team first. We've been using it for two months without issues. 
I will gladly work with k8s team if they wish to include it.
